[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 62.1.0", "wheel"]

[project]
authors = [{name = "Erich Nguyen", email = "erich.nguyen@outlook.com"}]
classifiers = [
  "Development Status :: 1 - Planning",
  "Natural Language :: English",
  "Programming Language :: Python",
  "Typing :: Typed",
]
description = "A simple experimental Python wrapper for the Ravy API."
keywords = [
  "API",
  "Python",
  "Ravy",
  "Wrapper",
]

license = {file = "LICENSE"}
maintainers = [
  {name = "Erich Nguyen", email = "erich.nguyen@outlook.com"},
]
name = "plane"
readme = "README.md"
requires-python = ">=3.7"
version = "0.1.0a"

dependencies = ["aiohttp"]

[project.urls]
homepage = "https://github.com/GoogleGenius/plane"
repository = "https://github.com/GoogleGenius/plane"

[tool.setuptools]
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
where = ["plane"]

[tool.pyright]
pythonVersion = "3.7"
typeCheckingMode = "strict"

[tool.black]
lineLength = 79
